language: ruby
bundler_args: --full-index --without development production
script: bundle exec rspec spec
env:
  - CI=true
rvm:
  - 1.9.3
  - 2.0.0
gemfile:
  - Gemfile
#branches:
#  only:
#    - master
