language: ruby
bundler_args: --full-index --without development production
before_install:
  - gem update --system
  - gem --version
script:
  - RAILS_ENV=test bundle exec rake db:migrate
  - bundle exec rake db:test:prepare
  - bundle exec rspec spec/ --format documentation
env:
  - CI=true
rvm:
  - 1.9.3
  - 2.0.0
gemfile:
  - Gemfile